# Generated by Django 3.1.6 on 2021-02-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='achievements',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
