# Generated by Django 3.1.6 on 2021-02-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0002_auto_20210223_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
